logo: line # add logo name
title: line - 千里之行
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: 千里之行 # add banner title
banner-desc:  # add banner description

# Author settings
author-pic: wechat.jpg # your photo
author-name: line # your name
about-author:  # about author
email: xianghengyong17@mails.ucas.edu.cn # your email
phone: 1314-131-0370 # your pnone number
website: https://xhy3054.github.io/ # you website

# Social link
google_url:  # add url link
twitter_url:   # add url link
wechat_url: 
qq_url:
weibo_url:
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier:  # add your discus identifier

# Newsletter
mailchimp: 2013211747@bupt.edu.cn # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: 

# Paginate
paginate: 9
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
